server:
  port: 8001

spring:
  config:
    import: optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}
  application:
    name: inyaa-gateway # 应用名称
  profiles:
    active: dev # 指定环境，默认加载 default 环境
  cloud:
    consul:
      # Consul 服务器地址
      host: 43.143.123.82
      port: 8500
      # 配置中心相关配置
      config:
        # 是否启用配置中心，默认值 true 开启
        enabled: true
        # 指定配置格式为 yaml
        format: YAML
        watch:
          # 是否开启自动刷新，默认值 true 开启
          enabled: true
          # 刷新频率，单位：毫秒，默认值 1000
          delay: 1000
      # 服务发现相关配置
      discovery:
        register: true                                # 是否需要注册
        instance-id: ${spring.application.name}-01    # 注册实例 id（必须唯一）
        service-name: ${spring.application.name}      # 服务名称
        port: ${server.port}                          # 服务端口
        prefer-ip-address: true                       # 是否使用 ip 地址注册
        # ip-address: ${spring.cloud.client.ip-address} # 服务请求 ip
    gateway:
      routes:
        - id: gateway  #请求 http://localhost:8100/data-service1/test会转发到data-producer服务，
          uri: lb://gateway  #在服务注册中心找服务名为 data-producer的服务，
          predicates:
            - Path=/gateway/**
          filters: # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1 # 转发之前去掉1层路径
  data:
    redis:
      # 连接地址
      host: 43.143.123.82
      # 端口
      port: 6379
      # 数据库
      database: 0
      # 用户名，如果有
      # username:
      # 密码，如果有
      password: yuxiaohao
  jpa:
    # 显示sql语句
    show-sql: true
    properties:
      hibernate:
        # 格式化sql语句
        format_sql: true
  datasource:
    url: jdbc:mysql://118.195.250.48:3306/inyaw?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: Yuxh3318375!
    driver-class-name: com.mysql.cj.jdbc.Driver

